name: Build macOS App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-macos:
    name: Build macOS Executable
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        pyinstaller CursoMedicina.spec

    - name: Archive the build
      run: |
        mkdir -p dist_output
        cp -R dist/CursoMedicina.app dist_output/
        tar -czvf CursoMedicina-macOS.tar.gz dist_output

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: CursoMedicina-macOS
        path: CursoMedicina-macOS.tar.gz
